### ISSUE TITLE
Travis-CI after success:

### ISSUE THREAD

**Issue by wangkanai** [angular-schule/angular-cli-ghpages#35]
How do I confirm travis-ci `after_success` to deploy `ngh` after `ng build --prod` was successful?
Right now I got this far
```console
The command "ng build --prod" exited with 0.
after_success.1
0.01s$ echo "wangkanai.com" > dist/CNAME
after_success.2
1.58s$ ngh --branch=master
An error occurred!
 Error: Unspecified error (run without silent option for detail)
    at /home/travis/.nvm/versions/node/v9.8.0/lib/node_modules/angular-cli-ghpages/node_modules/gh-pages/lib/index.js:232:19
    at _rejected (/home/travis/.nvm/versions/node/v9.8.0/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:844:24)
    at /home/travis/.nvm/versions/node/v9.8.0/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:870:30
    at Promise.when (/home/travis/.nvm/versions/node/v9.8.0/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/travis/.nvm/versions/node/v9.8.0/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:788:41)
    at /home/travis/.nvm/versions/node/v9.8.0/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:604:44
    at runSingle (/home/travis/.nvm/versions/node/v9.8.0/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:137:13)
    at flush (/home/travis/.nvm/versions/node/v9.8.0/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:112:11)
Done. Your build exited with 0.
```

this is my `.travis.yml`

```js
language: node_js
sudo: false
node_js:
  - '9'

branches:
  only:
    - dev

before_script:
  - npm install -g @angular/cli
  - npm install -g angular-cli-ghpages

script:
  - ng build --prod

after_success:
  - echo "wangkanai.com" > dist/CNAME
  - ngh --branch=master
```

**Comment by wangkanai** [comment]
So far I got to the point username & password
```console
The command "ng build --prod" exited with 0.
after_success.1
0.00s$ echo "wangkanai.com" > dist/CNAME
after_success.2
1.23s$ ngh --branch=master --no-silent
Cloning https://github.com/wangkanai/Wangkanai.git into ../../../.nvm/versions/node/v9.8.0/lib/node_modules/angular-cli-ghpages/node_modules/gh-pages/.cache
Cleaning
Fetching origin
Checking out origin/master
Removing files
Copying files
Adding all
Committing
Pushing
An error occurred!
 { ProcessError: remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/wangkanai/Wangkanai.git/'
    at ChildProcess.<anonymous> (/home/travis/.nvm/versions/node/v9.8.0/lib/node_modules/angular-cli-ghpages/node_modules/gh-pages/lib/git.js:47:23)
    at ChildProcess.emit (events.js:180:13)
    at maybeClose (internal/child_process.js:936:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
  code: 128,
  message: 'remote: Invalid username or password.\nfatal: Authentication failed for \'https://github.com/wangkanai/Wangkanai.git/\'\n',
  name: 'ProcessError' }
Done. Your build exited with 0.
```

**Comment by JohannesHoppe** [comment]
Please read more about GH_TOKEN:
https://github.com/angular-schule/angular-cli-ghpages/blob/master/README.md#extra
