### ISSUE TITLE
could not read Username for 'https://github.com'

### ISSUE THREAD

**Issue by tiberiuzuld** [angular-schule/angular-cli-ghpages#36]
```sh
D:\projects\angular-gridster2>npm run deploy-demo

> angular-gridster2@4.7.2 deploy-demo D:\projects\angular-gridster2
> ngh --dir=demo --no-silent --name='Tiberiu Zuld' --email='tiberiuzuld@gmail.com'

Cloning https://github.com/tiberiuzuld/angular-gridster2.git into node_modules\gh-pages\.cache

Cleaning

Fetching origin

Checking out origin/gh-pages

Removing files

Copying files

Adding all

Committing

Pushing

An error occurred!
 { ProcessError: bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No error

    at ChildProcess.<anonymous> (D:\projects\angular-gridster2\node_modules\gh-pages\lib\git.js:47:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  code: 128,
  message: 'bash: /dev/tty: No such device or address\nerror: failed to execute prompt script (exit code 1)\nfatal: could not read Username for
\'https://github.com\': No error\n',
  name: 'ProcessError' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-gridster2@4.7.2 deploy-demo: `ngh --dir=demo --no-silent --name='Tiberiu Zuld' --email='tiberiuzuld@gmail.com'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-gridster2@4.7.2 deploy-demo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!  debug.log

```

Tried to run this lib to publish my library on gh-pages but was not able to run it on:  
```
OS: Win10
Node: 8.11.0
Npm: 5.8.0
```
Tried with both the package installed globally and locally.
Tried these commands:
```sh
// will run from local package
npm run deploy-demo
// in package.json had "deploy-demo": "ngh --dir=demo"
// will run from global package
ngh --dir=demo --no-silent
ngh --dir=demo --no-silent --name='Tiberiu Zuld' --email='tiberiuzuld@gmail.com'
```

Running any of the commands I get to same error.

**Comment by Programazing** [comment]
I'd suggest reading [this](
https://github.com/angular-schule/angular-cli-ghpages/issues/14) first and see if that helps.

**Comment by tiberiuzuld** [comment]
Hi @Programazing ,
Followed the steps and created the ssh key. That didn't worked probably because of 2FA.

But when I run with GH_TOKEN as said [here](https://github.com/angular-schule/angular-cli-ghpages#extra) worked.

Thanks

**Comment by Programazing** [comment]
@tiberiuzuld  I use SSH with 2FA just fine.

I'm not sure why it didn't work for you but I'm happy you got it up and running with a token.

**Comment by DavidTheProgrammer** [comment]
Thanks @tiberiuzuld The token worked for me too. The SSH key failed

**Comment by VajiheHabibi** [comment]
Try using a normal Windows shell such as CMD.
