### ISSUE TITLE
Stuck on running GitHub page  command in Azure Pipeline

### ISSUE THREAD

**Issue by adnanebrahimi** [angular-schule/angular-cli-ghpages#47]
When The Asure Pipeline reaches at publishing to GitHub it sticks about 30 minutes then shuts down.

in Package.json I have:

"publish-to-git": "ngh --dir=dist/projectname",

**Azure Output:**
`2018-12-18T06:21:50.0328199Z [command]C:\Windows\system32\cmd.exe /D /S /C "D:\a\_tool\node\10.14.2\x64\npm.cmd run publish-to-git"`

`2018-12-18T06:48:15.6137049Z ##[error]The operation was canceled.`

**Comment by JohannesHoppe** [comment]
I have seen similar issues with node.js tasks running endlessly on Azure Dev Ops. 
Try to change the Agent pool to "Hosted Ubuntu" or "Hosted VS2017".

Does that help?

**Comment by adnanebrahimi** [comment]
It's getting better now!
now I can see what is the problem:
Log file attached.
`
[command]/opt/hostedtoolcache/node/10.14.2/x64/bin/npm run publish-to-git
2018-12-18T16:54:55.2497427Z *** An error occurred!
2018-12-18T16:54:55.2498000Z 
2018-12-18T16:54:55.2499128Z 
2018-12-18T16:54:55.2499981Z > one-pass@0.0.0 publish-to-git /home/vsts/work/1/s
2018-12-18T16:54:55.2500757Z npm ERR! code ELIFECYCLE
2018-12-18T16:54:55.2501259Z > npx ngh --dir=dist/one-pass
2018-12-18T16:54:55.2501875Z npm ERR! errno 1
2018-12-18T16:54:55.2501915Z 
2018-12-18T16:54:55.2502742Z npm ERR! one-pass@0.0.0 publish-to-git: `npx ngh --dir=dist/one-pass`
2018-12-18T16:54:55.2502822Z Error: Unspecified error (run without silent option for detail)
2018-12-18T16:54:55.2503483Z npm ERR! Exit status 1
2018-12-18T16:54:55.2503852Z     at /opt/hostedtoolcache/node/10.14.2/x64/lib/node_modules/angular-cli-ghpages/node_modules/gh-pages/lib/index.js:232:19
2018-12-18T16:54:55.2504497Z npm ERR! 
2018-12-18T16:54:55.2504843Z     at _rejected (/opt/hostedtoolcache/node/10.14.2/x64/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:844:24)
2018-12-18T16:54:55.2505765Z npm ERR! Failed at the one-pass@0.0.0 publish-to-git script.
2018-12-18T16:54:55.2506087Z     at /opt/hostedtoolcache/node/10.14.2/x64/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:870:30
2018-12-18T16:54:55.2506748Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-12-18T16:54:55.2507565Z     at Promise.when (/opt/hostedtoolcache/node/10.14.2/x64/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:1122:31)
2018-12-18T16:54:55.2508243Z 
2018-12-18T16:54:55.2508689Z     at Promise.promise.promiseDispatch (/opt/hostedtoolcache/node/10.14.2/x64/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:788:41)
2018-12-18T16:54:55.2509368Z npm ERR! A complete log of this run can be found in:
2018-12-18T16:54:55.2509786Z     at /opt/hostedtoolcache/node/10.14.2/x64/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:604:44
2018-12-18T16:54:55.2510902Z npm ERR!     /home/vsts/.npm/_logs/2018-12-18T16_54_55_149Z-debug.log
2018-12-18T16:54:55.2511416Z     at runSingle (/opt/hostedtoolcache/node/10.14.2/x64/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:137:13)
2018-12-18T16:54:55.2511994Z     at flush (/opt/hostedtoolcache/node/10.14.2/x64/lib/node_modules/angular-cli-ghpages/node_modules/q/q.js:125:13)
2018-12-18T16:54:55.2512592Z     at process._tickCallback (internal/process/next_tick.js:61:11)`
[log_12_11.zip](https://github.com/angular-schule/angular-cli-ghpages/files/2691461/log_12_11.zip)

**Comment by JohannesHoppe** [comment]
As stated in the message, run without silent option for details
