### ISSUE TITLE
Deploying results in error on Linux

### ISSUE THREAD

**Issue by rajinder-yadav** [angular-schule/angular-cli-ghpages#49]
This use to work, but it's been a while since I deployed. Following the steps from the README now fails in an error.

## Versions
Angular: ^7.2.0
angular-cli-ghpages: ^0.5.3

Step one, build goes well (The "dist" folder does not contain a subfolder).

```
$ ng build --prod --base-href="http://dynomightcss.com/"
                                                                                 
Date: 2019-01-20T11:42:06.394Z
Hash: 5a3ccc8818540c70d030
Time: 38591ms
chunk {0} runtime.b57bf819d5bdce77f1c7.js (runtime) 1.41 kB [entry] [rendered]
chunk {1} main.dd74da47309df22e6f90.js (main) 1.42 MB [initial] [rendered]
chunk {2} polyfills.85b8de986383d623e591.js (polyfills) 41 kB [initial] [rendered]
chunk {3} styles.1f8b4bee48110b4ecff6.css (styles) 117 kB [initial] [rendered]
chunk {scripts} scripts.0409edb92abecdc246d4.js (scripts) 9.37 kB [entry] [rendered]
```

Step two, deploy fails.

```
$ npx angular-cli-ghpages
*** An error occurred!

Error: Unspecified error (run without silent option for detail)
    at /home/yadav/projects/dm-css/website/dynomightcss/node_modules/gh-pages/lib/index.js:232:19
    at _rejected (/home/yadav/projects/dm-css/website/dynomightcss/node_modules/q/q.js:844:24)
    at /home/yadav/projects/dm-css/website/dynomightcss/node_modules/q/q.js:870:30
    at Promise.when (/home/yadav/projects/dm-css/website/dynomightcss/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/yadav/projects/dm-css/website/dynomightcss/node_modules/q/q.js:788:41)
    at /home/yadav/projects/dm-css/website/dynomightcss/node_modules/q/q.js:604:44
    at runSingle (/home/yadav/projects/dm-css/website/dynomightcss/node_modules/q/q.js:137:13)
    at flush (/home/yadav/projects/dm-css/website/dynomightcss/node_modules/q/q.js:125:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by JohannesHoppe** [comment]
"run without silent option for detail"

**Comment by rajinder-yadav** [comment]
To be more helpful next time, would have more respectful to tell me to add the switch, "--no-silent". Kind of arrogant the way this was closed off. I don't think you meant this, but it came off really rude.
