### ISSUE TITLE
Deployed Site :Error: Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by Abhiskonda9994** [angular-schule/angular-cli-ghpages#52]
After building the site with:

ng build --prod --base-href "https;//<username>.github.io/<reponame>/

I can run the site with no issues on a local server.

However, during  publishing via ngh, 

the gitBash gives error as:-
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'fs-extra'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\Abhi\AppData\Roaming\npm\node_modules\angular-cli-ghpages\index.js:3:9)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

After installing & deploying  "fs-extra" he error still exist..
Plz help me.. 
@JohannesHoppe

**Comment by JohannesHoppe** [comment]
Please try out the latest version. `fs-extra` was updated in [gh-pages](https://github.com/tschaub/gh-pages)
